### PR TITLE
Fix arrays vs enum merge

### LINKED ISSUE #818: YAML array truncation during overlay deep merge (v2.9.10–2.9.12)
## Description

When applying an overlay that adds a sibling property to an object containing YAML arrays, `bump overlay` truncates existing arrays from 2 elements to 1.

This works correctly in `2.9.9` but breaks somewhere between `2.9.10` and `2.9.12`.

## Reproduction

**Base spec:**
```yaml
paths:
  /example/{id}:
    get:
      responses:
        200:
          content:
            application/json:
              examples:
                Success:
                  value:
                    data:
                      attributes:
                        coordinates:
                          point-a:
                            - 0.2
                            - 0.5
                          point-b:
                            - 0.5
                            - 0.5
                          point-c:
                            - 0.2
                            - 0.7
                          point-d:
                            - 0.5
                            - 0.7
```

**Overlay:**
```yaml
overlay: 1.0.0
info:
  title: Add deprecated field
  version: 1.0.0
actions:
  - target: $["paths"]["/example/{id}"]["get"]["responses"]["200"]["content"]["application/json"]["examples"]["Success"]["value"]["data"]["attributes"]
    update:
      some-new-field: []
```

**Expected result after `bump overlay`:**
All arrays retain their 2 elements (e.g. `point-b: [0.5, 0.5]`).

**Actual result with v2.9.12:**
Some arrays are truncated to 1 element:
```yaml
point-b:
  - 0.5
# missing second element
point-c:
  - 0.2
  - 0.7
```

The `point-b` array loses its second item after the overlay merge. Strict validation then fails with:
```
`point-b` property must NOT have fewer than 2 items.
```

## Environment

- **Working version:** `bump-cli@2.9.9`
- **Broken version:** `bump-cli@2.9.12` (resolved via `npx bump-cli@^2.9.9`)
- **OS:** Ubuntu (GitHub Actions runner) and macOS
- **Node:** v20.x

## Workaround

Pin `bump-cli` to `2.9.9` to avoid the regression.

### PR DESCRIPTION
**Pull request by fbraure**
Add an `afterEach` parameter to the `mergician` function to ensure:
 - Arrays are appended (not deduped)
 - Enums are deduped

Fixes #818 (arrays deduped) with an evolution of #791 (deduplicate enum)

### CODE REVIEW

File: src/core/overlay.ts [hunk 1]
```diff
@@ -115,6 +115,20 @@ export class Overlay {
   // The last path entry (e.g. "'price']" or '0]') contains a final
   // ']' so we need to remove it AND we need to replace single quotes
   // to double quotes AND FINALLY parse the element to transform the
+  // Deep merge objects using a module (built-in spread operator is only shallow)
```
Comment (paulRbr) [inline src/core/overlay.ts:115]: Why does this land in the middle of an existing comment of the `pathEntryToKey` function?

File: src/core/overlay.ts [hunk 2]
```diff
@@ -115,6 +115,20 @@ export class Overlay {
...
+  private mergeWithEnumDedup<T extends JSONSchema4Object>(target: T, update: JSONSchema4Object): T {
+    const merger = mergician({
+      afterEach({key, mergeVal}: {key: string; mergeVal: unknown}) {
```
Comment (paulRbr) [inline src/core/overlay.ts]: I don't understand this syntax, it seems as if the `afterEach` function is part of this class.

However it's a parameter of mergician.

Can you define the callback function as a variable first

```ts
    const afterEach = ({key, mergeVal}: {key: string; mergeVal: unknown}) => { ... }
```

And then just use it in mergician initialiser

```ts
    mergician({afterEach:})
```

File: src/core/overlay.ts [hunk 3]
```diff
@@ -115,6 +115,20 @@ export class Overlay {
   // The last path entry (e.g. "'price']" or '0]') contains a final
   // ']' so we need to remove it AND we need to replace single quotes
   // to double quotes AND FINALLY parse the element to transform the
+  // Deep merge objects using a module (built-in spread operator is only shallow)
+  private mergeWithEnumDedup<T extends JSONSchema4Object>(target: T, update: JSONSchema4Object): T {
```
Comment (paulRbr) [inline src/core/overlay.ts]: Do you really need a `T extends JSONSchema4Object` generic type ?

Why don't you use `JSONSchema4Object` directly?

File: src/core/overlay.ts (hunk 1 above)
Comment (fbraure) [reply src/core/overlay.ts:115]: Automatic linter fix 😑

File: src/core/overlay.ts [hunk 4]
```diff
@@ -112,6 +118,13 @@ export class Overlay {
     return action.description ? `Action '${action.description}'` : 'Action'
   }
 
+  // Deep merge objects using a module (built-in spread operator is only shallow)
+  private mergeWithEnumDedup(target: JSONSchema4Object, update: JSONSchema4Object): JSONSchema4Object {
+    const merger = mergician({afterEach: this.enumDedupAfterEach, appendArrays: true})
```
Comment (paulRbr) [inline src/core/overlay.ts]: I don't think we need to extract the afterEach function in an instance function (on `this`). It can live right here:


```suggestion
    const afterEach = ({key, mergeVal}: {key: string; mergeVal: unknown}): unknown => {
      if (key === 'enum' && Array.isArray(mergeVal)) {
        return [...new Set(mergeVal)]
      }
    }
    const merger = mergician({afterEach:, appendArrays: true})
```

Comment (fbraure) [reply src/core/overlay.ts]: I was my first implementation (your first suggestion), but it create a lint error: 

`  117:84  error  Move arrow function 'afterEach' to the outer scope  unicorn/consistent-function-scoping`

Comment (paulRbr) [reply src/core/overlay.ts]: Ah sorry.. Then I think I prefer your initial suggestion with the anonymous function:


```suggestion
    const merger = mergician({
      afterEach(options: {key: string; mergeVal: unknown}) {
        if (options.key === 'enum' && Array.isArray(options.mergeVal)) {
          return [...new Set(options.mergeVal)]
        }
      },
      appendArrays: true,
    })
```

Comment (fbraure) [reply src/core/overlay.ts]: Ok, done !

**Review by paulRbr — APPROVED** [review]
thanks for the quick fix!
