### PR TITLE
diff: add a `--fail-on-breaking` flag to fail on breaking changes

### LINKED ISSUE #444: Add a new option to fail on breaking changes diff
Let's add a CLI option to be able to make the process fail (return code != 0) in case the computed diff returns a breaking change.

Any ideas on the name of the option? `--breaking` or `--ci`, other?

### PR DESCRIPTION
**Pull request by paulRbr**
Closes #444

### CODE REVIEW

File: src/flags.ts [hunk 1]
```diff
@@ -78,6 +78,14 @@ const open = (options = {}): Parser.flags.IBooleanFlag<boolean> => {
   });
 };
 
+const breaking = (options = {}): Parser.flags.IBooleanFlag<boolean> => {
+  return flags.boolean({
+    char: 'F',
```
Comment (Polo2) [inline src/flags.ts:83]: What is the purpose of this char `'F'` ? How is it used ?

Comment (Polo2) [reply src/flags.ts:83]: How I understand, this is the shortcut for `--breaking` flag. And since `-B` is already for `--branch`, you had to select an other letter. `F` for `Force, right ?

**Review by Polo2 — COMMENTED** [review]
Code looks clear, but it's a bit difficult to understand the context.

Could you for example add an example in the `bump deploy --help` result? And maybe a bit more context in the PR description 🙏

File: src/flags.ts (hunk 1 above)
Comment (paulRbr) [reply src/flags.ts:83]: yes and `f` is already taken by the `format` flag.

**Comment by paulRbr** [comment]
> Code looks clear, but it's a bit difficult to understand the context.

Context is written in the associated issue #444

**Comment by paulRbr** [comment]
> Could you for example add an example in the `bump deploy --help` result? And maybe a bit more context in the PR description

The help content of the `diff` command (and not `deploy` as you mentioned) is already quite complete as there are 3 different examples. I don't think we should add yet another exemple for **each added flag**. That's why each flag are documented in the top of the help:

```
USAGE
  $ bump diff FILE [FILE2]

ARGUMENTS
  FILE   Path or URL to your API documentation file. OpenAPI (2.0 to 3.1.0) and AsyncAPI (2.x)
         specifications are currently supported.

  FILE2  Path or URL to a second API documentation file to compute its diff

OPTIONS
  -B, --branch=branch                   Branch name. Can be provided via BUMP_BRANCH_NAME environment
                                        variable

  -F, --ci                              Fail when diff has a breaking change

[...]
```

I believe this is enough in the CLI help context. We can however add more docs on our [help pages](https://docs.bump.sh/help/bump-cli/) if you think its necessary.

**Review by Polo2 — APPROVED** [review]
Many thanks for this PR, and your answers during the review, I'm glad to approve this PR, and I'm sure this feature will be helpful for some of our users 💙
